name: WASM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
        with:
          target: wasm32-unknown-unknown
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: cargo test
        working-directory: bindings/wasm
      - run: wasm-pack build bindings/wasm --target nodejs
